_BASE_: maskformer2stereo_R50_bs16_90k.yaml
MODEL:
  WEIGHTS:  "checkpoints/R-101.pkl" #"/home/nstarli/Mask2Former/work_dirs/r101_48classes_fixedmatching/model_final.pth"
  RESNETS:
    DEPTH: 101
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
